Fix 100% wide table issue (#1463)
zim-desktop-wiki/zim-desktop-wiki pull request #1474
Opened 2021-05-28 05:41 UTC by VivekThazhathattil

modified:   zim/plugins/tableeditor.py
- By default, InsertedObjectWidget's expand flag is set to True, and
  that causes the abnormal table width. Changed the flag to False
  from within the tableViewWidget class to avoid that issue.

- set toolbar to adjust to its natural size than the existing size of
  (300, -1) as whenever the toolbar comes into view, last column sizes
  are annoyingly readjusted.

2021-05-28 11:28 UTC, introt requested changes
Great work! I'd lose the `set_resizable` and `set_reorderable` as their changes aren't saved and submit them in another PR after working that out.

2021-05-28 11:28 UTC, introt commented on zim/plugins/tableeditor.py
> +		InsertedObjectWidget.expand = False;
No need to call InsertedObjectWidget, `self.expand = False` works

2021-05-28 11:28 UTC, introt commented on zim/plugins/tableeditor.py
> +			tview_column.set_reorderable(True);
Reordering and resizing are lost on page reload. Remove the semicolons for consistency; they're not needed

2021-05-29 07:57 UTC, introt commented
One more change request: remove the semicolon on line 326. You might also want to edit out "enabled columns to resize and reorder" from the PR for clarity. Thanks for your cooperation!

2021-05-29 08:22 UTC, VivekThazhathattil commented
oops, sorry for that!

2021-05-29 09:01 UTC, introt approved these changes
All good, thanks for your contribution!

2021-09-14 19:25 UTC, closed without merging