Fix German translation for score
zim-desktop-wiki/zim-desktop-wiki pull request #1928
Opened 2022-02-13 16:28 UTC by dehesselle

This PR fixes a mistranslation in the German localization.

"score" as in music, not "score" as in grading.

2022-02-13 18:40 UTC, introt reviewed
Thanks! Could you please add the context clue ("`"score" as in music, not "score" as in grading.`") to the plugin source as well?

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/3e9064f2dda99b66e26de8adbf566b6fef1b32c5/zim/plugins/scoreeditor.py#L68

2022-02-13 18:55 UTC, dehesselle commented
Isn't this sufficient?
https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/3e9064f2dda99b66e26de8adbf566b6fef1b32c5/zim/plugins/scoreeditor.py#L4-L5

2022-02-13 19:03 UTC, introt commented
No, because translators using the web ui only see the following context, albeit surrounded by a fancy gooey:

```
#. menu item
#: zim/gui/searchdialog.py:150 zim/plugins/scoreeditor.py:68
msgid "Score"
```

(which is most likely how we ended up here; I remember another issue being caused by a translator mistakenly translating the context clue instead of the string)

2022-02-13 19:05 UTC, introt requested changes

2022-02-13 19:05 UTC, introt commented on translations/de.po
>  #: zim/gui/searchdialog.py:150 zim/plugins/scoreeditor.py:68
Took me a while to notice, but the translation is correct - for the search result scoring. The plugin needs to be modified.

2022-02-13 19:11 UTC, introt commented on translations/de.po
>  #: zim/gui/searchdialog.py:150 zim/plugins/scoreeditor.py:68
I suggest changing the visible string to "Music Score", because it's an item in a menu and should be unambiguous in any language

2022-02-13 19:12 UTC, introt commented on translations/de.po
>  #: zim/gui/searchdialog.py:150 zim/plugins/scoreeditor.py:68
@dehesselle yes it does:

https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/a9917c94a033a2ebf57bcd4ee111f023b14b03a0/translations/de.po#L1809-L1813

2022-02-22 19:54 UTC, jaap-karssenberg commented
Fixed the translation key to "Music Score" - you should now be able to set proper German translation via the Weblate interface. Thanks for the input!

2022-02-22 19:54 UTC, closed without merging