Fix KDE drag-n-drop bug
zim-desktop-wiki/zim-desktop-wiki pull request #2028
Opened 2022-05-04 07:32 UTC by alexivkin

On KDE page drag and drop is broken because, like #390 data absent, but unlike it, it's an empty string, not a None

2022-05-04 08:20 UTC, dehesselle commented on zim/plugins/pageindex/__init__.py
> +		if data is None or len(data)==0:
Please adopt the coding style as it is present in the file, i.e. add spaces. See here for example: https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/26de261b13f1560e315bb6914e0f91c61ed38ac0/zim/plugins/pageindex/__init__.py#L580

2022-05-04 21:48 UTC, alexivkin commented
feel free run an autofix for the style

2022-05-05 18:20 UTC, introt requested changes
Sorry, I don't think we have a linter configured for Zim's style. Additionally, PRs should be opened against the `develop` branch. I presume you made this edit from browser, so please redo the edit there: https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/85b6d81d31652042b1e9b007b211f9aab435047b/zim/plugins/pageindex/__init__.py#L557

2022-05-05 18:21 UTC, introt commented
Leaving this open for tracking purposes

2022-05-24 18:45 UTC, closed without merging