Replace usage of ``os.devnull`` with ``subprocess.DEVNULL``
zim-desktop-wiki/zim-desktop-wiki pull request #2308
Opened 2023-02-01 01:36 UTC by Toggoren

2023-02-14 20:05 UTC, jaap-karssenberg commented
Can you provide a rationale for this change ?

2023-02-15 13:03 UTC, Toggoren commented
> Can you provide a rationale for this change ?

Just a more fashionable  and modern way to do the same.

Similar merged pull requests:
- https://github.com/apache/airflow/pull/19354
- https://github.com/ipython/ipython/pull/13932
- https://github.com/conda/conda-build/pull/4565

2023-04-03 15:21 UTC, introt approved these changes
[Introduced](https://docs.python.org/3/library/subprocess.html) in Python 3.3, seems to do some file descriptor handling: https://github.com/python/cpython/issues/50120#issuecomment-1093466657 - though with `close_fds=True` it's not too relevant here.

2023-04-05 18:43 UTC, introt requested changes

2023-04-05 18:43 UTC, introt commented on zim/applications.py
>  					close_fds=True
`close_fds` defaults to `True` [from 3.2 onwards](https://docs.python.org/3/library/subprocess.html) while `subprocess.DEVNULL` was introduced in 3.3. If we're changing the code for modernization's sake, it should be done consistently on a given level (for example, a whole function/call at a time) or else we'll end up with a patchwork of modern and legacy code.

2023-04-05 18:51 UTC, introt commented on zim/applications.py
>  					close_fds=True
@jaap-karssenberg sorry for the hasty initial review; do you think we should have some guidelines on refactoring? Given the age of the code base, we do have some technical debt on tab, some of which can be paid now that we've bumped to 3.6+.

2023-04-14 22:44 UTC, randomguy commented
AFAIS this only adds a layer of indirection. A quick glance at os.py and subprocess.py from a Python 3.10 Linux install:
- os modules devnull is equivalent to os.path.devnull
- os.path is ntpath or posixpath determined dynamically on load and thus determines /dev/null platform dependently (makes sense, no such thing on Windows)
- subprocess.DEVNULL is a int constant determining various branching in subrpocess module (they should have underscored it by convention since it is a private member?)
- all the branching in subprocess module depending on subprocess.DEVNULL constants calls back to os.devnull AFAIS

2024-01-04 12:41 UTC, merged