Add support for screencapture on macOS
zim-desktop-wiki/zim-desktop-wiki pull request #2429
Opened 2023-07-22 12:05 UTC by dehesselle

- Introduce `screencapture` to support screen captures on macOS.
  - Using `-T0' for `full` is actually workaround (it says "delay 0 seconds") as this parameter cannot be set to `None`.
- Use `platform.system()` instead of os.name as we need a way to detect macOS ("Darwin").

2023-07-22 13:53 UTC, introt requested changes
Looks good, thanks!

Please update Plugins:Insert Screenshot to include "macOS: screencapture". If you want to go the extra mile, you may also add `(X11)` to the Linux options as per #2424 they don't work on Wayland

2023-07-22 14:11 UTC, dehesselle commented
As long as it stays a separate commit I'm not opposed to letting it piggyback on this PR.

2023-07-23 14:27 UTC, introt approved these changes
Thanks, LGTM!

2023-09-02 10:56 UTC, introt commented
...after  #2431?

2023-11-14 21:02 UTC, merged